{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SalesInvoiceDs\",\"Company\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.1380.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "ba0ff55e-286f-4006-ac1f-a874d9148a10",
        "fromColumn": "PaymDueDate",
        "fromTable": "Company",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1547e49a-8f34-4f5f-94c1-f76838d51166"
      },
      {
        "name": "c7407629-b5ff-473a-b421-3d516b732e4c",
        "fromColumn": "Company ",
        "fromTable": "SalesInvoiceDs",
        "toColumn": "Name",
        "toTable": "Company"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "SalesInvoiceDs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Company ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7107d8b1-f186-42ca-a30f-f7216181c543",
            "sourceColumn": "Company ",
            "summarizeBy": "none"
          },
          {
            "name": "InvoiceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "452ddb0f-4d4c-4650-9fd4-2b8108728da7",
            "sourceColumn": "InvoiceId",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d78fc23d-7fe2-4f03-a99e-4a0c9bca835c",
            "sourceColumn": "Item",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a40a0448-9033-44f5-b353-cc892eff7ce1",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dade47cf-bb36-4b5b-b64c-0904c6e5f0ba",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ce418d5-dfb5-451e-8414-239c8903843d",
            "sourceColumn": "SalesPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4a2819f3-659f-48d9-97ad-20b6915f3be1",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5599da55-5a26-4379-addc-b734977bca01",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesUnitTxt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c224252-8439-4091-896d-2f8bc76a54c6",
            "sourceColumn": "SalesUnitTxt",
            "summarizeBy": "none"
          },
          {
            "name": "FormLetterRemarksTxt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5a4ca21-92a5-459a-ace4-f41e27db2f66",
            "sourceColumn": "FormLetterRemarksTxt",
            "summarizeBy": "none"
          },
          {
            "name": "HeaderNotes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c137e1c-9b62-49c0-b459-2a08eb77283c",
            "sourceColumn": "HeaderNotes",
            "summarizeBy": "none"
          },
          {
            "name": "BankAccountNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b743ebfc-124f-4749-adcc-9f31242b848e",
            "sourceColumn": "BankAccountNum",
            "summarizeBy": "sum"
          },
          {
            "name": "ShowTotals1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9487b3a1-8415-4b15-ad2e-3c547d9a9b40",
            "sourceColumn": "ShowTotals1",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencySymbol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b67419eb-6061-4368-b4a8-3cd29024f206",
            "sourceColumn": "CurrencySymbol",
            "summarizeBy": "none"
          },
          {
            "name": "CashDisc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b5a4d35c-a1df-4b24-9eb4-a247a0487c25",
            "sourceColumn": "CashDisc",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "71ffefb1-0545-4b20-89b7-0146b2ab2471",
        "partitions": [
          {
            "name": "SalesInvoiceDs",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\r.bhalekar\\Downloads\\Invoice.xlsx\"), null, true),",
                "    SalesInvoiceDs_Sheet = Source{[Item=\"SalesInvoiceDs\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(SalesInvoiceDs_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Company \", type text}, {\"InvoiceId\", type text}, {\"Item\", type text}, {\"Description\", type text}, {\"Quantity\", Int64.Type}, {\"SalesPrice\", Int64.Type}, {\"Discount\", Int64.Type}, {\"Amount\", Int64.Type}, {\"SalesUnitTxt\", type text}, {\"FormLetterRemarksTxt\", type text}, {\"HeaderNotes\", type any}, {\"BankAccountNum\", Int64.Type}, {\"ShowTotals1\", type text}, {\"CurrencySymbol\", type text}, {\"CashDisc\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_26f0c15c-f3d1-40c0-b803-1a73d4d3ee45",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "52175183-d2b1-4f60-9a38-7095371685f6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9c0f1397-0ea5-45c1-8f37-f754c6023969",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ebdb3792-9d1e-4a27-bd3a-5ccb7f6f73a6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d6d59f98-ae14-46d4-bdc0-70ad1d0cd46c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c8640ee5-e78a-4471-a804-02f3c6bfb1b3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "05a52b85-e845-4007-a1fb-06dbafd499d9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "079ac364-d46b-4991-839b-e7ce87b76eae",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9a46ab1a-987a-436e-a79f-cc48a7c188e6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "dbce406a-ac11-410c-bec3-31344f187d36",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "041dc61e-c711-4cc8-ab59-36d62ecca078",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2294ab64-ed1b-4ca0-b968-342b215e75df",
                "ordinal": 3
              }
            ],
            "lineageTag": "488d89aa-f152-4037-8a77-f5bf09a474e5"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "0e1f1d2f-ce2d-453e-a317-28d19d111806",
        "partitions": [
          {
            "name": "DateTableTemplate_26f0c15c-f3d1-40c0-b803-1a73d4d3ee45",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Company",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5904df24-07cf-4ff8-b34f-5a8aded234a0",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e0c56b0-6238-4fba-9a4e-304b169b6165",
            "sourceColumn": "Address",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bd03caa-fd1c-410e-90fd-39c208f33878",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bb98b96-dd70-467a-b39a-9bef833ac1be",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "ZipCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bc00aa0a-e4d8-4d42-8b83-16613b213c87",
            "sourceColumn": "ZipCode",
            "summarizeBy": "count"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72815161-3967-460b-9173-c5688f1e0c20",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed94a4f7-6f21-4e81-bc04-6a91c065fbd8",
            "sourceColumn": "Phone",
            "summarizeBy": "sum"
          },
          {
            "name": "Website",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "770b4e61-af69-401b-8ff8-58e67bdfecea",
            "sourceColumn": "Website",
            "summarizeBy": "none"
          },
          {
            "name": "PaymTermDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9aa3c970-79f7-416f-aa67-bad9be8561fe",
            "sourceColumn": "PaymTermDescription",
            "summarizeBy": "none"
          },
          {
            "name": "PaymDueDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "077e91d4-c9c1-4fcc-8c3d-609df4dd48f2",
            "sourceColumn": "PaymDueDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1547e49a-8f34-4f5f-94c1-f76838d51166"
                },
                "isDefault": true,
                "relationship": "ba0ff55e-286f-4006-ac1f-a874d9148a10"
              }
            ]
          },
          {
            "name": "Column11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c01b07a2-e45d-4e99-9d81-d7aa018b16c4",
            "sourceColumn": "Column11",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f26041f5-d167-48d9-8497-47e5c6ffa5c3",
        "partitions": [
          {
            "name": "Company",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\r.bhalekar\\Downloads\\Invoice.xlsx\"), null, true),",
                "    Company_Sheet = Source{[Item=\"Company\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Company_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Name\", type text}, {\"Address\", type text}, {\"City\", type text}, {\"State\", type text}, {\"ZipCode\", Int64.Type}, {\"Country\", type text}, {\"Phone\", Int64.Type}, {\"Website\", type text}, {\"PaymTermDescription\", type text}, {\"PaymDueDate\", type date}, {\"Column11\", type any}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([Name] <> null))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_1547e49a-8f34-4f5f-94c1-f76838d51166",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d95a6f85-a20b-4ec8-b479-04014f6349d8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "07f4986e-f275-4f4d-a6bf-e9ebd9c7cc59",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5c81d086-7960-4ab3-895b-74fb529c0646",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "82ec59f3-d620-46d2-8286-9952ae5ad8a6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "ec17f716-42c7-4e88-9736-b4865019dc70",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fc5179e9-3152-4cf7-9191-cc5c6a0aa92b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "70c51652-7d65-434b-8f5c-9bedb26cf3d1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f33b5a88-fa74-4456-90e2-1b97e4f2d039",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7d270bee-73d9-4ab2-8435-522524ce39e9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "69556872-9057-4881-b3de-ad0ac40b0b22",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a948c772-1d09-4d06-ba4e-c87124d6bed7",
                "ordinal": 3
              }
            ],
            "lineageTag": "a5a4e7c3-9fc0-4d9b-8fe8-c4a3b0b87886"
          }
        ],
        "isHidden": true,
        "lineageTag": "7b690398-069f-4a8f-a376-6fc29f5c0767",
        "partitions": [
          {
            "name": "LocalDateTable_1547e49a-8f34-4f5f-94c1-f76838d51166",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Company'[PaymDueDate])), 1, 1), Date(Year(MAX('Company'[PaymDueDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}